spring:
  application:
    name: spring-sunshine
  ai:
    openai:
      api-key:
      base-url: https://openrouter.ai/api/v1
      chat:
        completions-path: /chat/completions
        options:
          model: x-ai/grok-4.1-fast

    google:
      genai:
        api-key:
        chat:
          options:
            model: gemini-2.5-flash-lite

sunshine:
  client:
    connect-timeout: 3000
    response-timeout: 5000
    retry:
      max-attempts: 3
      backoff: 1000